name: 'Devops Card Notifier'
description: 'forked from https://github.com/jenschelkopf/project-card-moved-notification-action'
inputs:
  token:
    description: 'The GitHub authentication token.'
    required: false
    default: ${{ github.token }}
  assigneeFilter:
    description: 'Only send notifications for the specified assignees. Use comma seperated values.'
    default: ''
runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'bell'
  color: 'gray-dark'
